# the filter currently checks for words that are 3 or more characters.
---
ass: "*ss"
asses: "*ss*s"
asshole: "*ssh*l*"
assholes: "*ssh*l*s"
bastard: b*st*rd
beastial: b**st**l
beastiality: b**st**l*ty
beastility: b**st*l*ty
bestial: b*st**l
bestiality: b*st**l*ty
bitch: b*tch
bitcher: b*tch*r
bitchers: b*tch*rs
bitches: b*tch*s
bitchin: b*tch*n
bitching: b*tch*ng
blowjob: bl*wj*b
blowjobs: bl*wj*bs
bullshit: b*llsh*t
clit: cl*t
cock: c*ck
cocks: c*cks
cocksuck: c*cks*ck
cocksucked: c*cks*ck*d
cocksucker: c*cks*ck*r
cocksucking: c*cks*ck*ng
cocksucks: c*cks*cks
cum: c*m
cummer: c*mm*r
cumming: c*mm*ng
cums: c*ms
cumshot: c*msh*t
cunillingus: c*n*ll*ng*s
cunnilingus: c*nn*l*ng*s
cunt: c*nt
cuntlick: c*ntl*ck
cuntlicker: c*ntl*ck*r
cuntlicking: c*ntl*ck*ng
cunts: c*nts
cyberfuc: cyb*rf*c
cyberfuck: cyb*rf*ck
cyberfucked: cyb*rf*ck*d
cyberfucker: cyb*rf*ck*r
cyberfuckers: cyb*rf*ck*rs
cyberfucking: cyb*rf*ck*ng
damn: d*mn
dildo: d*ld*
dildos: d*ld*s
dick: d*ck
dink: d*nk
dinks: d*nks
ejaculate: "*j*c*l*t*"
ejaculated: "*j*c*l*t*d"
ejaculates: "*j*c*l*t*s"
ejaculating: "*j*c*l*t*ng"
ejaculatings: "*j*c*l*t*ngs"
ejaculation: "*j*c*l*t**n"
fag: f*g
fagging: f*gg*ng
faggot: f*gg*t
faggs: f*ggs
fagot: f*g*t
fagots: f*g*ts
fags: f*gs
fart: f*rt
farted: f*rt*d
farting: f*rt*ng
fartings: f*rt*ngs
farts: f*rts
farty: f*rty
felatio: f*l*t**
fellatio: f*ll*t**
fingerfuck: f*ng*rf*ck
fingerfucked: f*ng*rf*ck*d
fingerfucker: f*ng*rf*ck*r
fingerfuckers: f*ng*rf*ck*rs
fingerfucking: f*ng*rf*ck*ng
fingerfucks: f*ng*rf*cks
fistfuck: f*stf*ck
fistfucked: f*stf*ck*d
fistfucker: f*stf*ck*r
fistfuckers: f*stf*ck*rs
fistfucking: f*stf*ck*ng
fistfuckings: f*stf*ck*ngs
fistfucks: f*stf*cks
fuck: f*ck
fucked: f*ck*d
fucker: f*ck*r
fuckers: f*ck*rs
fuckin: f*ck*n
fucking: f*ck*ng
fuckings: f*ck*ngs
fuckme: f*ckm*
fucks: f*cks
fuk: f*k
fuks: f*ks
gangbang: g*ngb*ng
gangbanged: g*ngb*ng*d
gangbangs: g*ngb*ngs
gaysex: g*ys*x
goddamn: g*dd*mn
hardcoresex: h*rdc*r*s*x
hell: h*ll
horniest: h*rn**st
horny: h*rny
hotsex: h*ts*x
jism: j*sm
jiz: j*z
jizm: j*zm
kock: k*ck
kondum: k*nd*m
kondums: k*nd*ms
kum: k*m
kumer: k*mm*r
kummer: k*mm*r
kumming: k*mm*ng
kums: k*ms
kunilingus: k*n*l*ng*s
lust: l*st
lusting: l*st*ng
mothafuck: m*th*f*ck
mothafucka: m*th*f*ck*
mothafuckas: m*th*f*ck*s
mothafuckaz: m*th*f*ck*z
mothafucked: m*th*f*ck*d
mothafucker: m*th*f*ck*r
mothafuckers: m*th*f*ck*rs
mothafuckin: m*th*f*ck*n
mothafucking: m*th*f*ck*ng
mothafuckings: m*th*f*ck*ngs
mothafucks: m*th*f*cks
motherfuck: m*th*rf*ck
motherfucked: m*th*rf*ck*d
motherfucker: m*th*rf*ck*r
motherfuckers: m*th*rf*ck*rs
motherfuckin: m*th*rf*ck*n
motherfucking: m*th*rf*ck*ng
motherfuckings: m*th*rf*ck*ngs
motherfucks: m*th*rf*cks
niger: n*gg*r
nigger: n*gg*r
niggers: n*gg*rs
orgasim: "*rg*s*m"
orgasims: "*rg*s*ms"
orgasm: "*rg*sm"
orgasms: "*rg*sms"
phonesex: ph*n*s*x
phuk: ph*k
phuked: ph*k*d
phuking: ph*k*ng
phukked: ph*kk*d
phukking: ph*kk*ng
phuks: ph*ks
phuq: ph*q
pis: p*ss
piss: p*ss
pisser: p*ss*r
pissed: p*ss*d
pisser: p*ss*r
pissers: p*ss*rs
pises: p*ss*s
pisses: p*ss*s
pisin: p*ss*n
pissin: p*ss*n
pising: p*ss*ng
pissing: p*ss*ng
pisof: p*ss*ff
pissoff: p*ss*ff
porn: p*rn
porno: p*rn*
pornography: p*rn*gr*phy
pornos: p*rn*s
prick: pr*ck
pricks: pr*cks
pussies: p*ss**s
pusies: p*ss**s
pussy: p*ssy
pusy: p*ssy
pussys: p*ssys
pusys: p*ssys
shit: sh*t
shited: sh*t*d
shitfull: sh*tf*ll
shiting: sh*t*ng
shitings: sh*t*ngs
shits: sh*ts
shitted: sh*tt*d
shitter: sh*tt*r
shitters: sh*tt*rs
shitting: sh*tt*ng
shittings: sh*tt*ngs
shitty: sh*tty
shity: sh*tty
slut: sl*t
sluts: sl*ts
smut: sm*t
spunk: sp*nk
twat: tw*t
카카오: '카카*'
kakao: 'kaka*'
최대천만원: '최대천만*'
돈내놔: '돈내*'
풰풰: '풰*'
쫘쫘: '쫘*'
쒜리: '쒜*'
잠지: '잠*'
운영진: '운영*'
니미: '니*'
부랄: '부*'
빠가: '빠*'
빠굴: '빠*'
샤발: '샤*'
샹년: '샹*'
섹년: '섹*'
시바: '시*'
시밤: '시*'
싸발: '싸*'
쒸발: '쒸*'
쒸벌: '쒸*'
씌벌: '씌*'
씨뎅: '씨*'
씨뱅: '씨*'
씨볼: '씨*'
씹세: '씹*'
씹탱: '씹*'
씹퉁: '씹*'
자지: '자*'
젖: '*'
죳: '*'
지랄: '지*'
고환: '고*'
꼭찌: '꼭*'
네미씹: '네미*'
늬기미: '늬기*'
늬믜럴: '늬믜*'
늬미랄: '늬미*'
니그미: '니그*'
니기미: '니기*'
씹창: '씹*'
음부: '음*'
병씬: '병*'
젓: '*'
좆: '*'
처녀막: '처녀*'
포르노: '포르*'
구입: '구*'
급매: '급*'
급처분: '급처*'
대출: '대*'
마진: '마*'
매입: '매*'
머니: '머*'
상담: '상*'
직거래: '직거*'
최고가: '최고*'
최저가: '최저*'
충전: '충*'
판매: '판*'
환전: '환*'
호로: '호*'
유방: '유*'
자궁: '자*'
개쉙: '개*'
개쉑: '개*'
시밝: '시*'
고객센터: '고객센*'
담당자: '담당*'
운영자: '운영*'
관리자: '관리*'
admin: 'admi*'
guest: 'gues*'
manager: 'manage*'
master: 'maste*'
vip: 'vi*'
고객: '고*'
신고: '신*'
ㅅㅂㄹㅁ: 'ㅅㅂㄹ*'
벼엉신: '벼엉*'
변섹: '변*'
병쉰: '병*'
병신: '병*'
보X: '보*'
보오지: '보오*'
보쥐: '보*'
보지: '보*'
보짓물: '보짓*'
붕신: '붕*'
븅신: '븅*'
브랄: '브*'
빙신: '빙*'
빠구리: '빠구*'
빠라: '빠*'
빠큐: '빠*'
빡돌아: '빡돌*'
빤쓰: '빤*'
빤쥬: '빤*'
빤쯔: '빤*'
빨아: '빨*'
빨어: '빨*'
뻐지: '뻐*'
뻐큐: '뻐*'
뻑꺼: '뻑*'
뽀개: '뽀*'
뽀르노: '뽀르*'
뽀사: '뽀*'
뽀지: '뽀*'
뽀찌: '뽀*'
뽀카머니: '뽀카머*'
뽀커머니: '뽀커머*'
뽀큐: '뽀*'
뾰큐: '뾰*'
삐꾸: '삐*'
사까시: '사까*'
새꺄: '새*'
새끼: '새*'
색스: '색*'
성기구: '성기*'
세꺄: '세*'
세끼: '세*'
세엑스: '세엑*'
섹s: '섹*'
섹소리: '섹소*'
섹수: '섹*'
섹스: '섹*'
섹쑤: '섹*'
섹쓰: '섹*'
수고료: '수고*'
쉐뀌: '쉐*'
쉐끼: '쉐*'
쉑: '*'
쉬벌년: '쉬벌*'
쉬파: '쉬*'
쉬팔: '쉬*'
쉬퐁: '쉬*'
스벌놈: '스벌*'
스와: '스*'
스와핑: '스와*'
스왑: '스*'
습탱이: '습탱*'
시끼: '시*'
시댕: '시*'
시발: '시*'
시불: '시*'
시키: '시*'
시파: '시*'
시팔: '시*'
시펄: '시*'
십딱: '십*'
십새: '십*'
십탱이: '십탱*'
싸가지: '싸가*'
싸줘: '싸*'
싹동: '싹*'
싹바: '싹*'
싹퉁: '싹*'
쌍너엄: '쌍너*'
쌍넘: '쌍*'
쌍녀언: '쌍녀*'
쌍년: '쌍*'
쌍놈: '쌍*'
쌍뇬: '쌍*'
쌔낑: '쌔*'
쌕쓰: '쌕*'
쌰꺄: '쌰*'
썅년: '썅*'
썅놈: '썅*'
써글: '써*'
써버럴: '써버*'
썩을: '썩*'
쎄엑스: '쎄엑*'
쑤셔: '쑤*'
쒜: '*'
쒸파: '쒸*'
쒸팍: '쒸*'
쒸펄: '쒸*'
쓰바: '쓰*'
쓰발: '쓰*'
쓰버: '쓰*'
쓰벌: '쓰*'
쓰봉: '쓰*'
쓰불: '쓰*'
쓰블: '쓰*'
쓰으발: '쓰으*'
쓰파: '쓰*'
쓰팍: '쓰*'
씨댕: '씨*'
씨바: '씨*'
씨발: '씨*'
씨봉: '씨*'
씨불: '씨*'
씨블: '씨*'
씨빡: '씨*'
씨빨: '씨*'
씨파: '씨*'
씨팍: '씨*'
씨팔: '씨*'
씹년: '씹*'
씹놈: '씹*'
씹발놈: '씹발*'
씹새: '씹*'
씹새끼: '씹새*'
씹쉐: '씹*'
108새끼: '108새*'
10새야: '10새*'
ㄴ: '*'
ㅂㅈㅈㅈ: 'ㅂㅈㅈ*'
ㅂ지: 'ㅂ*'
尼尾屍發老馬: '尼尾屍發老*'
갈아마실: '갈아마*'
갈아먹을: '갈아먹*'
강간: '강*'
개기냐: '개기*'
개년: '개*'
개놈: '개*'
개뇬: '개*'
개뼉다구: '개뼉다*'
개새끼: '개새*'
개색: '개*'
개섹: '개*'
개쌔끼: '개쌔*'
걸레: '걸*'
게년: '게*'
고마니: '고마*'
고머니: '고머*'
고모니: '고모*'
고스돕마니: '고스돕마*'
고스돕머니: '고스돕머*'
고스톱마니: '고스톱마*'
고스톱머니: '고스톱머*'
교성: '교*'
구녕: '구*'
구녘: '구*'
근친: '근*'
긍친: '긍*'
꺼져: '꺼*'
껍닥: '껍*'
꼰대: '꼰*'
꼰창: '꼰*'
꼴갑: '꼴*'
꼴깝: '꼴*'
꼴려: '꼴*'
꼽냐: '꼽*'
뇬: '*'
눈깔: '눈*'
니뽕: '니*'
니뿡: '니*'
니애미: '니애*'
니어미: '니어*'
니엄: '니*'
닝기미: '닝기*'
닥쳐: '닥*'
대가리: '대가*'
대갈: '대*'
대빵: '대*'
더른: '더*'
데져: '데*'
돌개이: '돌개*'
되져라: '되져*'
뒈져: '뒈*'
뒈져라: '뒈져*'
뒈진다: '뒈진*'
뒤지: '뒤*'
뒤진다: '뒤진*'
뒤질: '뒤*'
등신: '등*'
디져: '디*'
디질: '디*'
따먹: '따*'
딸딸: '딸*'
또라이: '또라*'
띠껍: '띠*'
띠발: '띠*'
띠방세: '띠방*'
띠블: '띠*'
띨: '*'
띱: '*'
마빡: '마*'
매춘: '매*'
매친: '매*'
머늬: '머*'
머늬판매: '머늬판*'
머늬팜: '머늬*'
머늬팝니다: '머늬팝니*'
머니사세요: '머니사세*'
머니세일: '머니세*'
머니장사: '머니장*'
머니판매: '머니판*'
머니팜: '머니*'
머니팝니다: '머니팝니*'
머저리: '머저*'
멍청이: '멍청*'
멍충: '멍*'
모니세일: '모니세*'
모니판매: '모니판*'
모니팜: '모니*'
모니팝니다: '모니팝니*'
모질이: '모질*'
목따: '목*'
문둥: '문*'
문디: '문*'
미췬: '미*'
미친: '미*'
미틴: '미*'
밑구멍: '밑구*'
바가: '바*'
박아: '박*'
발정: '발*'
번섹: '번*'
번쌕: '번*'
번쎅: '번*'
살해: '살*'
suicide: 'suicid*'
殺人: '殺*'
대마초: '대마*'
마약: '마*'
뽕: '*'
살인: '살*'
연쇄살인: '연쇄살*'
자살: '자*'
필로폰: '필로*'
히로뽕: '히로*'